### ISSUE TITLE
JavaScript Capstone Module 2 Group 

### ISSUE THREAD

**Issue by elassis** [elassis/module-2-capstone#21]
### Team Members ( 2 people ) 💻 ⚒️ :
- Enmanuel Lassis [@elassis](https://github.com/elassis)
- Juan Luis Gonzalez Giron

**Comment by mikenath223** [comment]
Hello  

You've done pretty well so far!
But for a few issues, you are almost done with this. Hang in there!


## Required Changes ♻️
_Please check the comments under the review._
- [x] Kindly ensure that every task gets assigned to team members. It seems in yours no task has been assigned. See the example below:

| Expected | Yours |
| ----- | ------ |
| <img src='https://user-images.githubusercontent.com/20563252/128746631-342f7d91-82db-48e8-a274-a8121c62e693.png' height='250px'> | <img src='https://user-images.githubusercontent.com/33323077/129628826-09e8a684-ba68-42f1-8e37-e99209a8444f.png' height='250px'> |

Happy coding, Cheers! 🚀🚀

Do feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, whether it is valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by elassis** [comment]
thank you

**Comment by mikenath223** [comment]
Hello there  

Your project is complete!  There is nothing else to say 🛳 
Congratulations! 🎉 

Happy coding. Cheers! 🚀🚀

If you feel something isn't clear enough you can leave a question or comment in the Issue thread.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
